name: formulario_warao
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # formz: ^0.7.0
  flutter_localization: ^0.2.0
  google_maps_flutter: ^2.6.1
  phone_text_field: any
  # flutter_osm_plugin: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
